### This notebook is to demo the iterative subgraph extraction procedure


In [1]:
import mgcpy
import numpy as np
#np.random.seed(8889)
from sklearn.metrics import adjusted_rand_score
from sklearn.cluster import KMeans
import graspy
from graspy.embed import AdjacencySpectralEmbed 
from graspy.simulations import sbm
from graspy.plot import heatmap, pairplot
import pandas as pd

from mgcpy.independence_tests.dcorr import DCorr
from mgcpy.independence_tests.mgc.mgc import MGC

#### Creating the simulated data

In [2]:
#1. create simulation graphs: Let's create the data for the 1st class with probability 0.3
 
block1= np.ones((20,20))*0.3
block2 = np.ones((20,180))*0.2
block3 = np.ones((180,20))*0.2
block4 = np.ones((180,180))*0.3
block = np.block([[block1, block2], [block3, block4]])
class1=[]
for i in range(100):
    class1.append(block)
len(class1)
    

100

In [10]:
print(class1[0].shape)
type(class1[0].shape)

(200, 200)


tuple

In [11]:
print(class1[0].shape[0])

200


In [6]:
### Creating class 2, prob class 0.4

blo1 = np.ones((20,20))*0.4
blo2 = np.ones((20,180))*0.2
blo3 = np.ones((180,20))*0.2
blo4 = np.ones((180,180))*0.3

blo = np.block([[blo1,blo2],[blo3,blo4]])

class2=[]
for i in range(100):
    class2.append(blo)
len(class2)


100

In [7]:
class2

[array([[0.4, 0.4, 0.4, ..., 0.2, 0.2, 0.2],
        [0.4, 0.4, 0.4, ..., 0.2, 0.2, 0.2],
        [0.4, 0.4, 0.4, ..., 0.2, 0.2, 0.2],
        ...,
        [0.2, 0.2, 0.2, ..., 0.3, 0.3, 0.3],
        [0.2, 0.2, 0.2, ..., 0.3, 0.3, 0.3],
        [0.2, 0.2, 0.2, ..., 0.3, 0.3, 0.3]]),
 array([[0.4, 0.4, 0.4, ..., 0.2, 0.2, 0.2],
        [0.4, 0.4, 0.4, ..., 0.2, 0.2, 0.2],
        [0.4, 0.4, 0.4, ..., 0.2, 0.2, 0.2],
        ...,
        [0.2, 0.2, 0.2, ..., 0.3, 0.3, 0.3],
        [0.2, 0.2, 0.2, ..., 0.3, 0.3, 0.3],
        [0.2, 0.2, 0.2, ..., 0.3, 0.3, 0.3]]),
 array([[0.4, 0.4, 0.4, ..., 0.2, 0.2, 0.2],
        [0.4, 0.4, 0.4, ..., 0.2, 0.2, 0.2],
        [0.4, 0.4, 0.4, ..., 0.2, 0.2, 0.2],
        ...,
        [0.2, 0.2, 0.2, ..., 0.3, 0.3, 0.3],
        [0.2, 0.2, 0.2, ..., 0.3, 0.3, 0.3],
        [0.2, 0.2, 0.2, ..., 0.3, 0.3, 0.3]]),
 array([[0.4, 0.4, 0.4, ..., 0.2, 0.2, 0.2],
        [0.4, 0.4, 0.4, ..., 0.2, 0.2, 0.2],
        [0.4, 0.4, 0.4, ..., 0.2, 0.2, 0.2],
        ..

#### Finding the features using ASE

In [8]:
ase = AdjacencySpectralEmbed()
ase1 = [ase.fit_transform(graphss) for graphss in class1]
ase2 = [ase.fit_transform(graphsss) for graphsss in class2]

#### Creating class labels

In [9]:
class_labe0 = np.zeros((200,1))
class_label1  = np.ones((200,1))


#### Iterative vertex screening method

#### we need to decide how many vertices we want to keep after the screening 

In [12]:
### Just following the paper

k = 1
vertices = class1[0].shape[0]

while remainingVert >1:
    for features in ase1: ##here will have to define the variable so it takes in both ase1 and ase2
        p_value, metadata = mgc.p_value(features, class_label1, replication_factor = 100)
        #mgc_statistic, test_statistic_metadata = mgc.test_statistic(features, class_label1) ##perhaps don't need this
    threshold= 0.5
    iterationVert = 
    k += 1
    
    
